name: Hyprland # Replace this name with your image name
id: hyprland-vib # Replace this ID with your image ID
stages:
- id: build
  base: ghcr.io/vanilla-os/core:main # Optionally, Replace this image URL with a different one i.e. nvidia:main, etc
  singlelayer: false
  labels:
    maintainer: self-maintained # Optionally, Replace this with your name
  args:
    DEBIAN_FRONTEND: noninteractive # Set the image environment as non-interactive
  
  # Commands to run first before building the modules
  runs:
    commands:
      - echo 'APT::Install-Recommends "1";' > /etc/apt/apt.conf.d/01norecommends

  modules:
  # Put your custom actions before this comment
  - name: running-steps
    type: includes
    includes:
      - modules/00-initial-setup.yml
      - modules/01-fsguard.yml
      - modules/05-shell.yml
      - modules/10-packages.yml
      - modules/20-hyprland-packages.yml
      - modules/99-cleanup.yml
      # - modules/.yml

      # remote modules:
      # Sample GitHub remote module in the format: `gh:your-name/your-repo:branch:modules/file.yml`
      - gh:vanilla-os/dev-image:main:modules/00-basics.yml 
      - https://raw.githubusercontent.com/Vanilla-OS/dev-image/main/modules/05-go.yml # Sample full URL remote module

